### ISSUE TITLE
Changing SAT name for watermark

### ISSUE THREAD

**Issue by maufox1** [Digitelektro/MeteorDemod#100]
Now that M-2 3 and M-2 4 are available, how to change name of sat automatically according to sat pass? Could %sat% be implemented or start meteordemod with a different settings.ini file? Thank you

**Comment by Digitelektro** [comment]
You need to add a new section to settings.ini for M2-4. Then use the -sat METEOR-M-2-4 command line parameter. There is already a branch with the correct settings, soon it will be merged to beta, until you can check it here:
[](https://github.com/Digitelektro/MeteorDemod/tree/feature/meteor_m_2_4_support)

**Comment by maufox1** [comment]
> You need to add a new section to settings.ini for M2-4. Then use the -sat METEOR-M-2-4 command line parameter. There is already a branch with the correct settings, soon it will be merged to beta, until you can check it here: https://github.com/Digitelektro/MeteorDemod/blob/feature/meteor_m_2_4_support/resources/settings.ini

Thank you for your prompt reply. I did add the new section for M2-4 in v2.5.5 and it works fine. However the setting for the watermark is still "Text=MeteorDemod %version% by Digitelektro\nMETEOR M2-3\n%date%". My point is "nMETEOR M2-3" should be a variable. On another note, I have tried the new settings with v2.6.3 beta and no watermark appears on the pictures. Is it intended to be like that?

**Comment by maufox1** [comment]
Thank youSent from my iPhoneOn 11 Mar 2024, at 17:49, Digitelektro ***@***.***> wrote:﻿
I think I have a version where this has been fixed, I just haven't merged it to beta yet! Will get back to you soon when I sorted these issues out.

**Comment by Digitelektro** [comment]
Now that M2-4 is back I finally fixed the issue. Indeed the text was hard coded, now I corrected it. Fix is available on beta branch now. Soon I will make a release.

**Comment by Digitelektro** [comment]
Meteordemod 2.6.5 is released with the fix.
