### ISSUE TITLE
Meteordemod 2.6.5 make failed

### ISSUE THREAD

**Issue by creas002** [Digitelektro/MeteorDemod#105]
Meteordemod 2.6.5 make failed... 

make -j4     failed 

/home/pi/raspberry-noaa-v2/software/MeteorDemod/imageproc/tps.h:45:10: fatal error: opencv2/shape/shape_transformer.hpp: No such file or directory

[Meteor_make_error.txt](https://github.com/Digitelektro/MeteorDemod/files/14907566/Meteor_make_error.txt)

**Comment by Digitelektro** [comment]
Do you use raspiNOAA image? I believe this issue is coming from opencv custom build, and it is not including a required package. I have to update the readme

**Comment by creas002** [comment]
Yes, I do. I had been running meteordemod 2.6.3.  Yesterday upgraded opencv
, but still get the same error during meterdemod make

***@***.***:~/raspberry-noaa-v2/software/opencv/build$
/usr/local/bin/opencv_version
4.9.0-dev

**Comment by Digitelektro** [comment]
You need to recompile opencv, components must include shape, I added it to the comments:
`cd opencv/
mkdir build && cd build
cmake ../  -DBUILD_LIST=core,imgproc,imgcodecs,shape -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_SHARED_LINKER_FLAGS=-latomic
make -j4
sudo make install`

**Comment by creas002** [comment]
See attached log files for what I ran yesterday and again just now .

 I am sorry, but I don't see where you added it to them comments and I'm
trying to understand what you mean by components must include shape.

Thanks


[opencv.log](https://github.com/Digitelektro/MeteorDemod/files/14909699/opencv.log)


[meteordemod_make_shape_error.log](https://github.com/Digitelektro/MeteorDemod/files/14909700/meteordemod_make_shape_error.log)

**Comment by Digitelektro** [comment]
Sorry, not comments, I meant -DBUILD_LIST. I added shape to it, like this:
`-DBUILD_LIST=core,imgproc,imgcodecs,shape`

Please try to compile opencv like this, and lets see.

**Comment by creas002** [comment]
I used the modified -DBUILD_LIST, but I don't see where shape was installed or compiled.  See log, Thx

[opencv.log](https://github.com/Digitelektro/MeteorDemod/files/14909767/opencv.log)

I tried make on meteordemod and same error.

**Comment by Digitelektro** [comment]
hmm, I am clueless. I don't get why it is not including the shape module.
Maybe you should remove the custom build and install it this way:
`sudo apt install libopencv-dev python3-opencv`

**Comment by creas002** [comment]
pi@raspberrypi:~/raspberry-noaa-v2/software$ rm -rf opencv
pi@raspberrypi:~/raspberry-noaa-v2/software$ sudo apt install libopencv-dev python3-opencv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libopencv-dev is already the newest version (4.5.1+dfsg-5).
python3-opencv is already the newest version (4.5.1+dfsg-5).
0 upgraded, 0 newly installed, 0 to remove and 116 not upgraded.

pi@raspberrypi:~/raspberry-noaa-v2/software$ sudo dpkg -r libopencv-dev
(Reading database ... 186986 files and directories currently installed.)
Removing libopencv-dev (4.5.1+dfsg-5) ...
Processing triggers for man-db (2.9.4-2) ...
pi@raspberrypi:~/raspberry-noaa-v2/software$ sudo dpkg -r python3-opencv              
dpkg: dependency problems prevent removal of python3-opencv:
 meteordemod depends on python3-opencv.

dpkg: error processing package python3-opencv (--remove):
 dependency problems - not removing
Errors were encountered while processing:
 python3-opencv
pi@raspberrypi:~/raspberry-noaa-v2/software$ sudo dpkg -r meteordemod   
(Reading database ... 186965 files and directories currently installed.)
Removing meteordemod (2.6.3) ...
dpkg: warning: while removing meteordemod, directory '/home/pi/.config' not empty so not removed
pi@raspberrypi:~/raspberry-noaa-v2/software$ sudo dpkg -r python3-opencv
(Reading database ... 186933 files and directories currently installed.)
Removing python3-opencv (4.5.1+dfsg-5) ...

# Reinstall based on suggestion

pi@raspberrypi:~/raspberry-noaa-v2/software$ sudo apt install libopencv-dev python3-opencv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  opencv-doc
The following NEW packages will be installed:
  libopencv-dev python3-opencv
0 upgraded, 2 newly installed, 0 to remove and 116 not upgraded.
Need to get 0 B/1,189 kB of archives.
After this operation, 6,288 kB of additional disk space will be used.
Selecting previously unselected package libopencv-dev.
(Reading database ... 186929 files and directories currently installed.)
Preparing to unpack .../libopencv-dev_4.5.1+dfsg-5_armhf.deb ...
Unpacking libopencv-dev (4.5.1+dfsg-5) ...
Selecting previously unselected package python3-opencv.
Preparing to unpack .../python3-opencv_4.5.1+dfsg-5_armhf.deb ...
Unpacking python3-opencv (4.5.1+dfsg-5) ...
Setting up python3-opencv (4.5.1+dfsg-5) ...
Setting up libopencv-dev (4.5.1+dfsg-5) ...
Processing triggers for man-db (2.9.4-2) ...

# Try to make meteordemod 2.6.5 again
pi@raspberrypi:~/raspberry-noaa-v2/software/MeteorDemod/build$ make -j4
[ 28%] Built target libcorrect
[ 28%] Built target sgp4
[ 31%] Building CXX object CMakeFiles/meteordemod.dir/imageproc/projectimage.cpp.o
[ 31%] Building CXX object CMakeFiles/meteordemod.dir/main.cpp.o
[ 33%] Building CXX object CMakeFiles/meteordemod.dir/imageproc/tps.cpp.o
[ 35%] Building CXX object CMakeFiles/meteordemod.dir/decoder/meteordecoder.cpp.o
In file included from /home/pi/raspberry-noaa-v2/software/MeteorDemod/imageproc/tps.cpp:1:
/home/pi/raspberry-noaa-v2/software/MeteorDemod/imageproc/tps.h:45:10: fatal error: opencv2/shape/shape_transformer.hpp: No such file or directory
   45 | #include <opencv2/shape/shape_transformer.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/meteordemod.dir/build.make:134: CMakeFiles/meteordemod.dir/imageproc/tps.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/pi/raspberry-noaa-v2/software/MeteorDemod/imageproc/projectimage.h:7,
                 from /home/pi/raspberry-noaa-v2/software/MeteorDemod/imageproc/projectimage.cpp:1:
/home/pi/raspberry-noaa-v2/software/MeteorDemod/imageproc/tps.h:45:10: fatal error: opencv2/shape/shape_transformer.hpp: No such file or directory
   45 | #include <opencv2/shape/shape_transformer.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/meteordemod.dir/build.make:108: CMakeFiles/meteordemod.dir/imageproc/projectimage.cpp.o] Error 1
In file included from /home/pi/raspberry-noaa-v2/software/MeteorDemod/imageproc/projectimage.h:7,
                 from /home/pi/raspberry-noaa-v2/software/MeteorDemod/main.cpp:19:
/home/pi/raspberry-noaa-v2/software/MeteorDemod/imageproc/tps.h:45:10: fatal error: opencv2/shape/shape_transformer.hpp: No such file or directory
   45 | #include <opencv2/shape/shape_transformer.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/meteordemod.dir/build.make:82: CMakeFiles/meteordemod.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/meteordemod.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
pi@raspberrypi:~/raspberry-noaa-v2/software/MeteorDemod/build$

**Comment by creas002** [comment]
Not sure why GitHub striked through all my text above, but all the text was meant to be read

**Comment by Digitelektro** [comment]
Ohh my god! I know someone had the same problem, and I don't know how he eventually fixed it. I think he told me it was "Vince's" image.

**Comment by Digitelektro** [comment]
What if you try to install meteordemod from the releases? If you do so please remove the old meteordemod as there were people who had two instances since make install put it different place than the dpkg installer.

https://github.com/Digitelektro/MeteorDemod/releases

**Comment by creas002** [comment]
See log again please, I removed my custom meteordemod and confirmed via dpkg no longer knows of meteordemod. Downloaded amd built again and same error from 2.6.5.
[removed_meteordemod_reinstalled.log](https://github.com/Digitelektro/MeteorDemod/files/14910032/removed_meteordemod_reinstalled.log)

**Comment by Digitelektro** [comment]
No, I meant to download the installer, not the source files! Download it from here:
https://github.com/Digitelektro/MeteorDemod/releases

**Comment by creas002** [comment]
Sorry, I misunderstood.  

pi@raspberrypi:~/raspberry-noaa-v2/software$ ls -l meteordemod*
-rw-r--r-- 1 pi pi 9471596 Mar 12 21:29 meteordemod_2.6.3_armhf.deb
-rw-r--r-- 1 pi pi 9465996 Apr  8 15:10 meteordemod_2-6-5_armfh_raspberry_bullseye.deb
pi@raspberrypi:~/raspberry-noaa-v2/software$ rm -rf MeteorDemod
pi@raspberrypi:~/raspberry-noaa-v2/software$ sudo dpkg -i meteordemod_2-6-5_armfh_raspberry_bullseye.deb
Selecting previously unselected package meteordemod.
(Reading database ... 186954 files and directories currently installed.)
Preparing to unpack meteordemod_2-6-5_armfh_raspberry_bullseye.deb ...
Unpacking meteordemod (2.6.5) ...
Setting up meteordemod (2.6.5) ...

pi@raspberrypi:~/raspberry-noaa-v2/software$ meteordemod -help    
MeteorDemod Version 2.6.5
-h      --help  Print help
-t      --tle   TLE file required for pass calculation
-i      --input Input S file containing softbits
-o      --output        Output folder where generated files will be placed
-d      --date  Specify pass date, format should be dd-mm-yyyy
-f      --format        Output image format (bmp, jpg)
-s      --symbolrate    Set symbol rate for demodulator
-m      --mode  Set demodulator mode to qpsk or oqpsk
-diff   --diff  Use differential decoding (Maybe required for newer satellites)
-int    --int   Deinterleave (Maybe required for newer satellites)
-b      --brokenM2      Broken M2 modulation
-c      --compmaxage    Maximum image age in hours for creating composite image
-sat    --satellite     Name of the satellite settings in settings.ini file

terminate called after throwing an instance of 'std::runtime_error'
  what():  Satellite name is not given in command line arguments!
Aborted

**Comment by Digitelektro** [comment]
So it does work now :)

**Comment by Digitelektro** [comment]
It is a mystery why compiling cannot be done... I will try to make a fresh raspbian install and try to reproduce the issue. But I believe something is messed up on that image.

**Comment by creas002** [comment]
I tried meteordemod using a M2-4 wav captured this morning, in process now. Never found lock. It's still running right now.  

pi@raspberrypi:~$ /usr/bin/meteordemod -m oqpsk -diff 1 -s 72000 -sat METEOR-M2-4 -t /home/pi/raspberry-noaa-v2/tmp/orbit.tle -f jpg -i /srv/audio/meteor/METEOR-M2-4-20240408-044917.wav
Input is a .wav file, processing it...
 Carrier: -25.36Hzz      Lock detector: 0.23     isLocked: 0     OutputSize: 128.66Mb Progress: 100.00%

**Comment by Digitelektro** [comment]
Don't forget that now both satellites are on 137.9Mhz! :)

**Comment by creas002** [comment]
Thanks, I had forgotten. I've not switched M2-4 over yet.  So I will need to try and older WAV file. Thanks for the reminder.

**Comment by creas002** [comment]
Bam!!!  Houston, we have lock on M2-4, Excellent, Thank you sir!!!!

**Comment by Digitelektro** [comment]
Are you available on discord APT server?

**Comment by creas002** [comment]
I am.  creas002

**Comment by perhp** [comment]
I managed to get it working by recompiling OpenCV. Make sure to include the opencv_contrib repository as well, and reference it during the compilation process. The opencv_contrib repository contains the shape module.
