### ISSUE TITLE
Additional forgotten commands when installing OpenCV

### ISSUE THREAD

**Issue by mihajlo2003petkovic** [Digitelektro/MeteorDemod#15]
You had written commands for OpenCV installation, after `cd opencv/` you forgot to include `mkdir build && cd build` otherwise cmake will try to find Cmake fole in the `/home/pi/` instead of `opencv/`.

**Comment by Digitelektro** [comment]
Hi! 
Thank you for noting! 
Readme is corrected in commit 5b00079c9688ecf4553f9c11878ca2034f2d0339
