### ISSUE TITLE
QT5 Error

### ISSUE THREAD

**Issue by colinluthier** [Digitelektro/MeteorDemod#2]
While trying to install this I got this error:

CMake Error at cmake/OpenCVFindLibsGUI.cmake:18 (find_package):
  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:707 (include)

**Comment by Digitelektro** [comment]
Could you please provide more information? What is your operating system? What commands did you use before you get this error message? Did you follow the steps from readme? I don't understand why QT5 is involved in the building process.

**Comment by colinluthier** [comment]
It was user error. I was having a hard time sorting out how to install this and google led me to compiling openccv. That was hwere the error was, not your code. I figured out how to use opencv without a fresh compile. Sorry about that. Closing.
