### ISSUE TITLE
error while building meterodemod

### ISSUE THREAD

**Issue by 3B8-Vick** [Digitelektro/MeteorDemod#27]
pi@raspberrypi:~/opencv $ pwd
/home/pi/opencv
pi@raspberrypi:~/opencv $ cmake ../  -DBUILD_LIST=core,imgproc,imgcodecs -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_SHARED_LINKER_FLAGS=-latomic
-- Build type: Release
CMake Error at /usr/share/cmake-3.18/Modules/ExternalProject.cmake:2555 (message):
  No download info given for 'sgp4' and its source directory:

   /home/pi/external/sgp4

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/ExternalProject.cmake:3206 (_ep_add_download_command)
  CMakeLists.txt:23 (ExternalProject_Add)

CMake Error at /usr/share/cmake-3.18/Modules/ExternalProject.cmake:2555 (message):
  No download info given for 'libcorrect' and its source directory:

   /home/pi/external/libcorrect

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/ExternalProject.cmake:3206 (_ep_add_download_command)
  CMakeLists.txt:32 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "/home/pi/opencv/CMakeFiles/CMakeOutput.log".

**Comment by 3B8-Vick** [comment]
Error sorted out

**Comment by Digitelektro** [comment]
I guess you forget to run `git submodule update --init --recursive`
