### ISSUE TITLE
settings.ini - documentation

### ISSUE THREAD

**Issue by KiwiInNZ** [Digitelektro/MeteorDemod#55]
Can the settings.ini file be documented to explain in more detail what each configuration does in the readme, ideally with some examples.

**Comment by KiwiInNZ** [comment]
With some assistance from the author, I've created a tutorial for using MeteorDemod on my website.

https://kiwiweather.com/index.php/2022/12/17/meteordemod-tutorial-for-meteor-m-2/

Whilst this isn't a fully detailed description for every single possible setting, it should allow most people to be up and running using this awesome application.

**Comment by Digitelektro** [comment]
Thanks for the nice tutorial! Link added to readme.md
