### ISSUE TITLE
Equidistant composite projection - unexpected viewpoint

### ISSUE THREAD

**Issue by KiwiInNZ** [Digitelektro/MeteorDemod#59]
Equidistant composites can result in an unusual viewpoint which is less than ideal.

![equidistant_2022-12-03-19-37-18_221_composite](https://user-images.githubusercontent.com/51867737/205461161-c94049c1-f298-4cd8-8356-d0e286aad65a.jpg)

Not quite sure what is going wrong here, but given that the south pole is aligned with the right hand side of the image, I suspect there could be a link with where the code is setting a maximum / minimum value.

Source file for settings.ini and the .s and .tle files - https://kiwiweather.com/downloads/meteordemod.zip (339MB - let me know when you've downloaded this so I can remove it). I can supply the .wav files, but that is about twice as much space!

Commands used to generate the images:
meteordemod -i 2022-12-01-16-41-42-METEOR-M_2.s -t 2022-12-01-16-41-42-METEOR-M_2weather.tle -f jpg -d 01-12-2022
meteordemod -i 2022-12-01-18-21-57-METEOR-M_2.s -t 2022-12-01-18-21-57-METEOR-M_2weather.tle -f jpg -d 01-12-2022
meteordemod -i 2022-12-02-06-41-13-METEOR-M_2.s -t 2022-12-02-06-41-13-METEOR-M_2weather.tle -f jpg -d 02-12-2022

**Comment by Digitelektro** [comment]
I downloaded the files. I will update the ticket once I have update.

**Comment by KiwiInNZ** [comment]
Closing this issue as unable to reproduce. What is likely to have happened is that the composite was made using passes several days apart.

**Comment by KiwiInNZ** [comment]
Reopening this one as I've been able to reproduce the problem.

Source data (1.3GB) to reproduce can be downloaded from - https://kiwiweather.com/downloads/Issue59.zip. Let me know when you've downloaded it so I can remove it.

The .s files were created from the .wav file using meteor_demod (https://github.com/dbdexter-dev/meteor_demod) which is currently better at extracting a few more scan lines from the .wav files.

Code used:
```
meteor_demod -B -r 72000 -m qpsk -o 2022-12-19-17-22-32-METEOR-M_2.s 2022-12-19-17-22-32-METEOR-M_2.wav
meteor_demod -B -r 72000 -m qpsk -o 2022-12-19-19-05-22-METEOR-M_2.s 2022-12-19-19-05-22-METEOR-M_2.wav
meteor_demod -B -r 72000 -m qpsk -o METEOR-M-2-20221220-074631.s METEOR-M-2-20221220-074631.wav
meteor_demod -B -r 72000 -m qpsk -o METEOR-M-2-20221220-060619.s METEOR-M-2-20221220-060619.wav
```

First processing the .wav files using MeteorDemod:
```
echo 1st
meteordemod -i ../src/2022-12-19-17-22-32-METEOR-M_2.wav -t ../src/2022-12-19-17-22-32-METEOR-M_2weather.tle -f jpg -d 19-12-2022
echo 2nd
meteordemod -i ../src/2022-12-19-19-05-22-METEOR-M_2.wav -t ../src/2022-12-19-19-05-22-METEOR-M_2weather.tle -f jpg -d 19-12-2022
echo 3rd
meteordemod -i ../src/METEOR-M-2-20221220-074631.wav -t ../src/orbit.tle -f jpg -d 19-12-2022
echo 4th
meteordemod -i ../src/METEOR-M-2-20221220-060619.wav -t ../src/orbit.tle -f jpg -d 19-12-2022
echo done
```
Although there are 3 different .tle files, the content for the Meteor M-2 satellite is identical.

This works well and produces a good composite, with this being just one example file. Everything looks good.
![equidistant_2022-12-20-16-48-23_221_composite-sm](https://user-images.githubusercontent.com/51867737/208599153-ee91c6f3-5beb-4c9c-b0a7-f461fdd1f6ae.jpg)

However next we'll process the .s files created by meteor_demod.
```
echo 1st
meteordemod -i ../src/2022-12-19-17-22-32-METEOR-M_2.s -t ../src/2022-12-19-17-22-32-METEOR-M_2weather.tle -f jpg -d 19-12-2022
echo 2nd
meteordemod -i ../src/2022-12-19-19-05-22-METEOR-M_2.s -t ../src/2022-12-19-19-05-22-METEOR-M_2weather.tle -f jpg -d 19-12-2022
echo 3rd
meteordemod -i ../src/METEOR-M-2-20221220-074631.s -t ../src/orbit.tle -f jpg -d 19-12-2022
echo 4th
meteordemod -i ../src/METEOR-M-2-20221220-060619.s -t ../src/orbit.tle -f jpg -d 19-12-2022
echo done
```
Looking at the .bmp files from each, you can see that more lines from each pass was extracted. However for compositing, you'd expect to see something very much like the first image, but with more content from each pass.

And in looking at each individual file, i.e. anything non-composited, everything looks fine.

The combination of the first two images:
![equidistant_2022-12-20-19-04-50_221_composite](https://user-images.githubusercontent.com/51867737/208599635-6af5ecdc-9b67-4f60-baec-d3e29abf8ec9.jpg)
There haven't combined well, with one image across the south pole and the other too far south? The X looks to be in the wrong place.

And then the first 3:
![equidistant_2022-12-20-19-06-06_221_composite](https://user-images.githubusercontent.com/51867737/208599732-46c54d81-4ad4-44ba-b718-985ab29c2a56.jpg)
This looks better, but at least one image is in the right place, possibly two, but one is too far south and the X is too far south.

And then the all 4:
![equidistant_2022-12-20-19-07-47_221_composite](https://user-images.githubusercontent.com/51867737/208599798-39d38318-019b-4681-91e6-bb0ef86fed3c.jpg)
This looks to have everything in the right place, but the viewpoint isn't great to see the image well.
