### ISSUE TITLE
Receiver location incorrectly marked

### ISSUE THREAD

**Issue by KiwiInNZ** [Digitelektro/MeteorDemod#60]
As per the example, the X to mark the receiver location is appearing in the wrong location.

![equidistant_221_2022-12-1-18-27-38](https://user-images.githubusercontent.com/51867737/205461345-9cc60e0d-3f27-47f6-8e14-a2bc1a419fbf.jpg)

From the settings.ini file (note - not the exact location of my receiver, but within 25km of it:
```
Latitude=-36.920
Longitude=-174.800
```
As per Google Maps, this is located within Auckland, not a significant distance out in the Pacific on what looks to be the same latitude, but a more easterly longitude.
![image](https://user-images.githubusercontent.com/51867737/205461420-3832a441-daac-4102-bb6a-b2871861d718.png)

What I suspect may be happening is that the longitude is impacted by a calculation linked to the current time in New Zealand being UTC + 13 since it is during our daylight savings time for being summer, the opposite for the northern hemisphere. We're normally on UTC + 12 over our winter.

Source file for settings.ini and the .s and .tle files - https://kiwiweather.com/downloads/meteordemod.zip (339MB - let me know when you've downloaded this so I can remove it). I can supply the .wav files, but that is about twice as much space!

Commands used to generate the images:
meteordemod -i 2022-12-01-16-41-42-METEOR-M_2.s -t 2022-12-01-16-41-42-METEOR-M_2weather.tle -f jpg -d 01-12-2022
meteordemod -i 2022-12-01-18-21-57-METEOR-M_2.s -t 2022-12-01-18-21-57-METEOR-M_2weather.tle -f jpg -d 01-12-2022
meteordemod -i 2022-12-02-06-41-13-METEOR-M_2.s -t 2022-12-02-06-41-13-METEOR-M_2weather.tle -f jpg -d 02-12-2022

**Comment by KiwiInNZ** [comment]
Meteordemod is a great tool and I'm really impressed by what it can do, so hoping that by logging these tickets that it can be improved further still.

**Comment by KiwiInNZ** [comment]
Note - the city locations from the shapefiles are being positioned correctly, e.g. where Wellington is positioned on the image below.
![image](https://user-images.githubusercontent.com/51867737/205462653-6b42e500-3e7f-40a7-bfc8-93b351260f3f.png)

**Comment by KiwiInNZ** [comment]
![equidistant_221_2022-12-1-18-27-38](https://user-images.githubusercontent.com/51867737/205468252-4b5d0189-ed17-40b3-b970-e2a494b2c3ad.jpg)
```
Latitude=-36.920
Longitude=-184.800
```
I got this result by increasing the longitude from 174.8 to 184.8, i.e. adding 10 degrees. It isn't perfectly aligned with this adjustment, but pretty close.

**Comment by Digitelektro** [comment]
> Meteordemod is a great tool and I'm really impressed by what it can do, so hoping that by logging these tickets that it can be improved further still.

No problem at all! I am happy that someone finally uses meteordemod that part of the Earth. I know lots of users across Europe, north America and someone in India, but nobody used it yet from the south! So it was not tested there.

There is a discord server for weather satellites, I'd like to invite you: https://discord.gg/zCApHGHB
There is a dedicated channel for meteordemod where I keep the people updated about meteordemod changes, and also you can chat with me, it is easier than communicating through Github tickets.

I downloaded the files, I will investigate the problems as my time allows it.

**Comment by Digitelektro** [comment]
Hi @KiwiInNZ
You set negative the longitude, that is the problem. See your attached picture from google maps.

Please use the following convention:
 - Latitude: North positive, South negative
 - Longitude: East positive,  West negative

Your Correct setting:
 - Latitude=-36.920
 - Longitude=174.800

**Comment by KiwiInNZ** [comment]
Fix validated with using the correct sign convention.
![equidistant_221_2022-12-1-18-27-10](https://user-images.githubusercontent.com/51867737/206271822-d89adc62-1670-4a5a-a15a-e988f0ce6824.jpg)
