### ISSUE TITLE
Boundaries seem to drift 

### ISSUE THREAD

**Issue by jeffreypkelly** [Digitelektro/MeteorDemod#64]
I have been noticing that boundary alignment seems to be on and off on different passes.
I download keps each day and clock time is accurate, don't know if the PC time clock varies.
Anyone else notice that?
![equidistant_rain_IR_2022-12-12-22-20-59_sm](https://user-images.githubusercontent.com/34376383/207605470-a08a0f4d-43bd-487d-99bd-5377fa9f7049.jpg)
![mercator_rain_IR_2022-12-14-12-0-29_sm](https://user-images.githubusercontent.com/34376383/207605490-6dd27eec-a3f4-471d-896c-c105f0c7c279.jpg)

**Comment by Digitelektro** [comment]
Hi @jeffreypkelly 
For me your pictures are look great! It is not possible to draw it perfectly aligned, it is completely normal if the map drawings are a few pixels off. 
Your PC clock doesn't affect it. Satellite onboard clock is used for the calculation.

**Comment by jeffreypkelly** [comment]
Oh good. Thanks for getting back! Please close.

**Comment by Digitelektro** [comment]
Okay, if you want to get in touch feel free to join to APT server on discord: https://discord.gg/FnPSQY5v
