### ISSUE TITLE
Cities marked in wrong country

### ISSUE THREAD

**Issue by Akito01** [Digitelektro/MeteorDemod#9]
With the equidistant render of Meteor I've noticed twice a wrong location marker.
I have seen both Brighton as well as Canberra located in Russia. With the other renders it's fine.
TLEs are updated on a daily basis.

**Comment by Digitelektro** [comment]
Can you please send me the .s file along with the .tle file? So I can investigate the problem. You can use wetranfer or similar to share the files. Thak you!

**Comment by Akito01** [comment]
I have uploaded a .s and .tle file here: [https://drive.google.com/file/d/1t8xthYsC7LxXJ0l9hV-HJD-2umcx9d4h/view?usp=sharing](url)

**Comment by Digitelektro** [comment]
Thank you! I am able to reproduce the problem, I do see Canberra in Russia. I will investigate what is the problem.

**Comment by Digitelektro** [comment]
Issue is fixed in commit 4bdd241ec656156de5dbfc6ec0d32c40c210d88c, it is on develop branch now, you can test it.

**Comment by Akito01** [comment]
Great! I can't reproduce it anymore now. Thanks!
